atualizando pom e workflow para analises com checkstyle, spotbugs e CLOC; reusable workflows

diff --git a/.github/workflows/ci-cd.yaml.yml b/.github/workflows/ci-cd.yaml.yml
--- a/.github/workflows/ci-cd.yaml.yml
+++ b/.github/workflows/ci-cd.yaml.yml
@@ -28,19 +28,11 @@ jobs:
       - name: Checkout do código
         uses: actions/checkout@v4
 
-      - name: Configurar JDK (Java 21)
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
+      - name: Criar pasta para os relatórios
+        run: mkdir -p reports/${{ github.ref_name }}
 
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
+      - name: Cache Maven
+        uses: ./.github/workflows/maven-cache.yml@main
 
       - name: Inicializar CodeQL
         uses: github/codeql-action/init@v4
@@ -48,13 +40,64 @@ jobs:
           languages: ${{ matrix.language }}
           queries: security-extended,security-and-quality
 
-      - name: Compilar o projeto
-        run: mvn compile -DskipTests
+      - name: Configurar JDK (Java 21) e compilar projeto com Maven
+        uses: ./.github/workflows/maven-compile.yml@main
 
       - name: Executar análise de CodeQL
         uses: github/codeql-action/analyze@v4
         with:
+          output: reports/${{ github.ref_name }}
           category: "/language:${{ matrix.language }}"
+
+      - name: Renomear arquivo SARIF
+        run: |
+          ORIGINAL="reports/${{ github.ref_name }}/${{ matrix.language }}.sarif"
+          NOVO="reports/${{ github.ref_name }}/codeql-results.sarif"
+          mv "$ORIGINAL" "$NOVO"
+
+      - name: Executar CLOC
+        uses: djdefi/cloc-action@6
+        with:
+          options: --exclude-lang=YAML --md --report-file=cloc.md
+
+      - name: Mover CLOC report
+        run: mv cloc.md reports/${{ github.ref_name }}/cloc.md
+
+      - name: Executar Checkstyle (Maven)
+        run: mvn checkstyle:checkstyle
+
+      - name: Preparar pasta para report do Checkstyle
+        run: mkdir -p reports/${{ github.ref_name }}/checkstyle-result
+
+      - name: Mover report Checkstyle
+        run: |
+          mv target/site/css reports/${{ github.ref_name }}/checkstyle-result/css
+          mv target/site/images reports/${{ github.ref_name }}/checkstyle-result/images
+          mv target/site/checkstyle.html reports/${{ github.ref_name }}/checkstyle-result
+
+      - name: Executar SpotBugs
+        run: mvn spotbugs:spotbugs
+
+      - name: Mover report SpotBugs
+        run: |
+          mv target/spotbugsXml.xml reports/${{ github.ref_name }}/spotbugs.xml
+          mv target/site/spotbugs.html reports/${{ github.ref_name }}/spotbugs.html
+
+      - name: Executar testes
+        run: |
+          mvn test -Dgroups=!Selenium -B || {
+            echo "::error::Alguns testes falharam. Revise os logs para detalhes.";
+            exit 1;
+          }
+
+      - name: Mover report JaCoCo
+        run: mv target/site/jacoco/ reports/${{ github.ref_name }}/jacoco
+
+      - name: Upload dos reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: "reports-${{ github.ref_name }}"
+          path: reports/${{ github.ref_name }}
 
   build:
     needs: analyse
@@ -64,42 +107,11 @@ jobs:
       - name: Checkout do código
         uses: actions/checkout@v4
 
-      - name: Configurar JDK (Java 21)
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-
       - name: Cache Maven
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
+        uses: ./.github/workflows/maven-cache.yml
 
-      - name: Compilar com Maven
-        run: |
-          mvn clean compile -B || { 
-            echo "::error::Falha na compilação do projeto. Verifique erros de sintaxe ou dependências ausentes."; 
-            exit 1; 
-          }
-
-      - name: Executar testes
-        run: |
-          mvn test -Dgroups=!Selenium -B || {
-            echo "::error::Alguns testes falharam. Revise os logs para detalhes.";
-            exit 1;
-          }
-
-      - name: Gerar relatório de cobertura
-        run: mvn jacoco:report
-
-      - name: Upload relatório de cobertura
-        uses: actions/upload-artifact@v4
-        with:
-          name: cobertura
-          path: target/site/jacoco
+      - name: Configurar JDK (Java 21) e compilar projeto com Maven
+        uses: ./.github/workflows/maven-compile.yml@main
 
       - name: Empacotar aplicação
         run: |
